language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

before_script:
  - mysql -e 'create database nexus1;'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash travis.sh
